# Generated by Django 3.1.7 on 2021-02-24 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_courses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseManager',
        ),
    ]
